# Generated by Django 3.1.7 on 2021-03-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='pricelookupevent',
            name='name',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
