# Generated by Django 3.1.7 on 2021-03-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210308_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelookupevent',
            name='ticker',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
