# Generated by Django 3.1.7 on 2021-03-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_pricelookupevent_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='one_off_scrape',
            field=models.BooleanField(default=False),
        ),
    ]
