# Generated by Django 3.1.7 on 2021-03-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_company_one_off_scrape'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='has_granular_scraping',
            field=models.BooleanField(default=False),
        ),
    ]
