# Generated by Django 3.1.7 on 2021-03-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_company_has_granular_scraping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelookupevent',
            name='ticker',
            field=models.CharField(default='appl', max_length=20),
            preserve_default=False,
        ),
    ]
