# Generated by Django 3.1.7 on 2021-03-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_company_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='scraping_scheduler_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
